import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Item {
    ColumnLayout {
        anchors.fill: parent; anchors.margins: 24; spacing: 14
        Text { text: "ATTENDANCE"; color: "#20C9FF"; font.pixelSize: 10; font.bold: true }
        Text { text: "Attendance Records"; color: "#F5FBFF"; font.pixelSize: 26; font.bold: true }
        Text { text: "Verified presence generated by the recognition engine."; color: "#64788B"; font.pixelSize: 11 }
        Rectangle {
            Layout.fillWidth: true; Layout.fillHeight: true
            color: "#0A1723"; radius: 13; border.color: "#142633"
            Text { anchors.centerIn: parent; text: "Attendance table will be connected to DatabaseManager."; color: "#64788B"; font.pixelSize: 12 }
        }
    }
}
